export const AssigendPapers = [
    { id: 1, userName: "Ocean", Title: "#00B8D9", },
    { id: 2, userName: "Blue", Title: "#0052CC" },
    { id: 3, userName: "Purple", Title: "#5243AA" },
    { id: 4, userName: "Red", Title: "#FF5630" },
    { id: 5, userName: "Orange", Title: "#FF8B00" },
    { id: 6, userName: "Yellow", Title: "#FFC400" },
    { id: 7, userName: "Green", Title: "#36B37E" },
    { id: 8, userName: "Forest", Title: "#00875A" },
    { id: 9, userName: "Slate", Title: "#253858" },
    { id: 10, userName: "Silver", Title: "#666666" },
    { id: 1, userName: "Ocean", Title: "#00B8D9", },
    { id: 2, userName: "Blue", Title: "#0052CC" },
    { id: 3, userName: "Purple", Title: "#5243AA" },
    { id: 4, userName: "Red", Title: "#FF5630" },
    { id: 5, userName: "Orange", Title: "#FF8B00" },
    { id: 6, userName: "Yellow", Title: "#FFC400" },
    { id: 7, userName: "Green", Title: "#36B37E" },
    { id: 8, userName: "Forest", Title: "#00875A" },
    { id: 9, userName: "Slate", Title: "#253858" },
    { id: 10, userName: "Silver", Title: "#666666" }
];